### ISSUE TITLE
Should make create Map to be unsafe?

### ISSUE THREAD

**Issue by quininer** [kalamay/vmap-rs#15]
The contents of mmap may be changed externally and violate Rust's mutability assumptions.

see https://github.com/danburkert/memmap-rs/issues/25 and https://users.rust-lang.org/t/how-unsafe-is-mmap/19635

**Comment by ghost** [comment]
Well what if someone writes to process memory and changing one of your struct's data? I think it can only be mutated by other process which you manage? I don't think its that unsafe
