### ISSUE TITLE
Can't create memory mapping greater than file

### ISSUE THREAD

**Issue by jean-airoldie** [kalamay/vmap-rs#17]
The following line...
https://github.com/kalamay/vmap-rs/blob/605bcd7c355bf2a1eca441540fa5717897bb1683/src/map.rs#L1458
...prevents the memory mapping from being greater than the size of the file. This behavior can be quite usefull if you want to create a large memory map without actually reserving the disk space. This way you can dynamically grow the underlying file without having to resize your mmap via mremap (which is really slow and painfull).

**Comment by kalamay** [comment]
Yeah, that is true, though it's a somewhat delicate issue as reading into the range outside of the file will result in a `SIGBUS`. Admittedly, this is a sometimes useful usage pattern, and I did originally have a means for doing just that. I had deprecated and then removed it for these safety concerns, but if this is something you need, I've had some thoughts on a way to do this in a somewhat safer way. Do you have any specific use cases in mind?

**Comment by jean-airoldie** [comment]
My original use case was to allocate a huge memory map ahead of time without needing to reallocate & synchronize between two threads.

However I just ended up using two memory maps pointing to the same file and dynamically resizing them. This approach slower because of the additional syscalls to resize the memory maps, but it's not a big deal since it happens rarely. Moreover, you don't need to deal with the additional virtual memory pressure of allocating a huge mmap ahead of time.

Maybe its too exotic of a use case to justify the hassle, so you can close the issue.

**Comment by kalamay** [comment]
This is something I've surely done in the past (in C), which is why I had something for it initially. But I'm rethinking things a bit here to make it safer. I'll close for now, but don't hesitate to reopen an issue if you find a need for it.
