### ISSUE TITLE
Map to real files

### ISSUE THREAD

**Issue by benlongo** [kalamay/vmap-rs#21]
Is it possible to allow mapping to real files instead of those created through `memfd_open`? I want to use the double `mmap` trick to get circular behavior for a queue that's also on disk, but I'm not sure if that's feasible.

**Comment by kalamay** [comment]
This library already implements circular behavior via the [`Ring`](https://docs.rs/vmap/0.5.1/vmap/io/struct.Ring.html) and [`InfiniteRing`](https://docs.rs/vmap/0.5.1/vmap/io/struct.InfiniteRing.html) types!
